### ISSUE TITLE
Styled title bar

### ISSUE THREAD

**Issue by jarsen** [wesbos/cobalt2-vscode#1]
It would be extra 🔥 if the title bar were styled an appropriate cobalt blue color.

See this [discussion](https://twitter.com/wesbos/status/907717433351426048) and also this [theme](https://github.com/whizkydee/vscode-material-palenight-theme/blob/master/themes/material-palenight-theme.json) as an example of what titleBar properties are available.

It looks like the keys are:
```json
    "titleBar.activeBackground"
    "titleBar.activeForeground"
    "titleBar.inactiveBackground"
    "titleBar.inactiveForeground"
```

**Comment by wesbos** [comment]
thanks - fixed in the next release later today

**Comment by jarsen** [comment]
Is the color #0047ab anywhere else in the theme? Seems like it is literally cobalt blue, which might be a bit bright?

**Comment by jarsen** [comment]
I have a commit that makes it match the tab bar but I have to rebase my fork real quick to do the P
