### ISSUE TITLE
Adjust filenames colors in VCS context

### ISSUE THREAD

**Issue by ArnaudRinquin** [wesbos/cobalt2-vscode#100]
As discussed on [twitter](https://twitter.com/wesbos/status/979395487513088001), the filenames colors in a VCS context are a bit weird, especially the ignored files which are displayed in super-bright-pink. The edited files in red is a bit weird as well, it's usually related to errors.

I suggest the following:

* new files : keep current green
* edited files : yellow
* ignored files : darker than regular files 

<img width="488" alt="screen shot 2018-03-29 at 09 36 15" src="https://user-images.githubusercontent.com/228886/38101295-c32866c0-3334-11e8-8d42-e0dc02ecfaab.png">

**Comment by abdelrahmanrifai** [comment]
The red color means that your file has an issue/problem, it will be yellow if it's edited and has no issue/problem.

**Comment by ArnaudRinquin** [comment]
Oh that's right.

<img width="487" alt="screen shot 2018-03-29 at 10 12 33" src="https://user-images.githubusercontent.com/228886/38102964-c7c730a8-3339-11e8-883d-cd5c18e38c19.png">

**Comment by JVPartanen** [comment]
I agree that git ignored pink color is bit awful as it is too close to error color and I think it would be better if it was the same dark grey as in default themes. You can of course add this line to user settings for a quick fix:

` "workbench.colorCustomizations": {
        "gitDecoration.ignoredResourceForeground": "#747476"
    }
`

**Comment by abdelrahmanrifai** [comment]
I'm the one who added that kinda pink color when `gitDecoration` first introduced months ago, I was trying to use colors that are declared already by @wesbos in https://github.com/wesbos/cobalt2-vscode/blob/master/theme/cobalt2.json file.

Let's agree on color here, then open a pull request.

I tried`#747476` however it's too dark, what about one of the following colors: `#aaaaaa`, `#fb94ff` or `#9effff` I got all of them from the same file mentioned above.

**Comment by abdelrahmanrifai** [comment]
Sorry, I just noticed that I have changed the `sideBar.foreground` into my settings to be much brighter.

So here is a comparison: _notice `node_modules` folder._

My settings:
```
"workbench.colorCustomizations": {
  "[Cobalt2]": {
    "gitDecoration.ignoredResourceForeground": "#aaa",
    "sideBar.foreground": "#f8f8f2"
  }
}
```
![v1](https://user-images.githubusercontent.com/4334778/38178175-708b99a6-360d-11e8-8ae4-e6228a33865c.png)

@JVPartanen suggestion:
```
"workbench.colorCustomizations": {
  "[Cobalt2]": {
    "gitDecoration.ignoredResourceForeground": "#747476"
  }
}
```
![v2](https://user-images.githubusercontent.com/4334778/38178202-ded09e84-360d-11e8-9b7b-94ff5ec1c332.png)

Others:
![v3](https://user-images.githubusercontent.com/4334778/38178249-f166593e-360e-11e8-926a-6cff951a041f.png)
![v4](https://user-images.githubusercontent.com/4334778/38178250-f19f627e-360e-11e8-9250-e0ac43d9b333.png)

**Comment by jeffersonlam** [comment]
Just chiming in to say I just installed cobalt2 and love it, except for the bright pink color on ignored files!

I like `#747476` for ignored files, as it's darker than the color `#aaaaaa` used for normal files but not too dark against the background. Alternatively, here are some other pre-existing colors darker than `#747476`:

- `#ffffff33` currently used in 1 place
- `#406179cc` currently used in 1 place
- `#3B5364` currently used in 2 places
