### ISSUE TITLE
editor.findMatchBackground for number is unreadable

### ISSUE THREAD

**Issue by kkurola** [wesbos/cobalt2-vscode#104]
When searching for an exact number the match is unreadable as editor.findMatchBackground color is too close to the color of the number.

![image](https://user-images.githubusercontent.com/1371294/38861614-a93a01d6-423b-11e8-91e0-f9f7b321a947.png)

**Comment by kapiljaveri** [comment]
Would love to submit a PR for this if you think adding some transparency work?

![screen shot 2018-10-03 at 10 28 38 pm](https://user-images.githubusercontent.com/6692991/46451406-c40df300-c75b-11e8-92f9-e553d6345bab.png)

![screen shot 2018-10-03 at 10 28 54 pm](https://user-images.githubusercontent.com/6692991/46451411-c708e380-c75b-11e8-962c-ddca20d98a48.png)

**Comment by palashmon** [comment]
Yup, that looks better. Can you search for the 256 number here and see how that looks also.

Regards!

**Comment by palashmon** [comment]
Yup, that looks better. Please submit a PR for this.

Regards!

**Comment by kapiljaveri** [comment]
Awesome, will do. Thanks!
