### ISSUE TITLE
HTML strings are same color as HTML Tag names

### ISSUE THREAD

**Issue by RichieRunner** [wesbos/cobalt2-vscode#105]
Believe they should be white? I've made no changes of my own.

![image](https://user-images.githubusercontent.com/20289967/39349701-b87b47be-49b0-11e8-84e2-231869181e94.png)

**Comment by palashmon** [comment]
This happens in `.js` files only, right? I looked into `.html` files and HTML strings seem to be in white color.

**Comment by RichieRunner** [comment]
It clearly is white for Bos though...

![image](https://user-images.githubusercontent.com/20289967/39913285-2516721c-54b6-11e8-8832-c5af28d087ce.png)

**Comment by grmnn** [comment]
I don't know if you have already any other fix for this, if so let me please know but I had the same problem, but found a way to fix this myself. 

I'm not sure if this breaks any other syntax highlighting, but for now everything else seems fine for me.

Open the command palette with `Ctrl+Shift+P ` and enter for `Developer: Inspect TM Scopes`. 
You can see which rules are applied to the specific line you are on with your cursor. 

For me it looked like this:
![wrong_highlighting](https://user-images.githubusercontent.com/42418362/44771133-70135b80-ab6a-11e8-9bbb-c82fa2930495.png)

So I opened `C:\Users\USERPROFILE\.vscode\extensions\wesbos.theme-cobalt2-2.1.6\theme\cobalt2.json`

and added following rule:
```
    {
      "name": "[JAVASCRIPT] - JSX - String Inside HTML",
      "scope": "meta.tag.jsx",
      "settings": {
        "foreground": "#e1efff"
      }
    },
```

Please let me know if I it worked for you or if there are any better fixes for this.

**Comment by fpigeonjr** [comment]
@grmnn Thanks! That worked for me.

**Comment by palashmon** [comment]
Closing this issue for now, please reopen if that is not the case.
