### ISSUE TITLE
hello~ it is question! not issue! html code not contrast, i want change html code color!

### ISSUE THREAD

**Issue by Loyide** [wesbos/cobalt2-vscode#106]
i think html tag is not contrast so i want change html color 

so i find it !

{
      "name": "[HTML] - Entity Name",
      "scope": "text.html.basic entity.name",
      "settings": {
        "foreground": "#9effff"
      }
    },

in cobalt2.json 

but it doesn't work!

i want know how to change html code color

l love coblat2!
thank you so much coblat2 programers~

**Comment by palashmon** [comment]
Try to change the scope like:

```json
"scope": "text.html.basic entity.name.tag",
```

**Comment by Loyide** [comment]
thank you for your answer but it is not work 
i'm use react so html tag exists in JSX 

get inspiration from your answers.
i'm trying change this code 

{
      "name": "[CSS] - Element Selector",
      "scope": "entity.name.tag",
      "settings": {
        "foreground": "#9effff"
      }
  },

so it is working!!

html tag color change !!
