### ISSUE TITLE
Add italic font style attribute support for babel syntax

### ISSUE THREAD

**Issue by sagarrabadiya** [wesbos/cobalt2-vscode#107]
When the cobalt2 syntax is applied and if i use one of the following syntax highlight then it doesn't make the props to italic font

https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring

https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel

but if i change the syntax to default javascript it make it italic correctly.

**Comment by sagarrabadiya** [comment]
use javascript react as your syntax highlight

**Comment by palashmon** [comment]
Closing this issue for now as this is related to other VS Code extension related. Not in the scope of the theme. Thanks!
