### ISSUE TITLE
class and def reserverd words are not colored diferently.

### ISSUE THREAD

**Issue by wsantos** [wesbos/cobalt2-vscode#109]
This make confuse to read, would be nice to have different colors for `def` and `class`

![image](https://user-images.githubusercontent.com/164633/40934480-d2d2a1f8-682c-11e8-95a7-5e6e81840dd7.png)

**Comment by wesbos** [comment]
can you post a sample file? Def should look similar to the JS version of classes

**Comment by wsantos** [comment]
Here it's:

```
from django.conf import settings
from django.http.request import QueryDict
from django.utils.encoding import (
    smart_bytes,
    smart_text,
)

from ipware import get_client_ip


class MyMiddleware(MiddlewareMixin):

    def process_response(self, request, response):

        client_ip, _ = get_client_ip(request)
        data = {
            'ip': client_ip,
            'user_agent': self.request.META.get('HTTP_USER_AGENT', '')
        }

        cookie_data = smart_text(
            base64.b64encode(smart_bytes(json.dumps(data))))

        response.set_cookie(
            key='name',
            value=cookie_data,
            max_age=60,
            domain=http_host or getattr(
                settings, 'SESSION_COOKIE_DOMAIN', '.consumeraffairs.com'
            )
        )
        return response
```
![image](https://user-images.githubusercontent.com/164633/40934802-e210725c-682d-11e8-919f-cff565a4d6ec.png)

**Comment by wsantos** [comment]
```python
from django.conf import settings
from django.http.request import QueryDict
from django.utils.encoding import (
    smart_bytes,
    smart_text,
)

from ipware import get_client_ip


class MyMiddleware(object):

    def process_response(self, request, response):

        client_ip, _ = get_client_ip(request)
        data = {
            'ip': client_ip,
            'user_agent': self.request.META.get('HTTP_USER_AGENT', '')
        }

        cookie_data = smart_text(
            base64.b64encode(smart_bytes(json.dumps(data))))

        response.set_cookie(
            key='name',
            value=cookie_data,
            max_age=60,
            domain=http_host or getattr(
                settings, 'SESSION_COOKIE_DOMAIN', '.site.com'
            )
        )
        return response
```

![image](https://user-images.githubusercontent.com/164633/40934946-6c3fe868-682e-11e8-873b-75a466e6426a.png)

**Comment by wesbos** [comment]
thanks - if any python devs want to tackle this I'd be very happy :D

**Comment by wsantos** [comment]
@wesbos This is my first vscode extension change/coding, hope everything looks okay :D

**Comment by wsantos** [comment]
@wesbos any update on this fix ? are you willing to merge ? or it needs more work ?

**Comment by yujinyuz** [comment]
Hi @wesbos,

Why is it that when installing the cobalt2 extensions, I'm not getting the version where this patch was merged?

When I checked the file `.vscode/extensions/wesbos.theme-cobalt2-2.1.6/theme/cobalt2.json`,
the file still contains:

```json
{
    "name": "Keyword",
    "scope": "keyword, storage.type.class.js",
    "settings": {
        "foreground": "#ff9d00"
    }
}
```

Has this not yet been pushed to the vscode market?

**Comment by yujinyuz** [comment]
I just checked the VSCode Market

`Last updated | 2/9/2018, 10:50:33 PM`

And this PR is around June of 2018. No wonder why I'm still getting the unpatched version.

Could you update this in the market @wesbos ? Thanks!
