### ISSUE TITLE
Id names don't highlight as strings

### ISSUE THREAD

**Issue by sebaslm** [wesbos/cobalt2-vscode#11]
When creating an id in an HTML tag the string value does not get highlighted as a string. It has the same colour of tags. It is working fine with other attributes like class, rel, href, alt, etc.

![screen shot 2017-09-13 at 23 04 27](https://user-images.githubusercontent.com/20850740/30378857-f66f53c4-98d7-11e7-8098-6747cad58bad.png)

**Comment by wesbos** [comment]
fixed in the next update! Thanks

**Comment by palashmon** [comment]
Hi @wesbos just sent you a DM on twitter. Please check it out whenever you are free. Thanks!
