### ISSUE TITLE
Theme for active indent guide

### ISSUE THREAD

**Issue by andrewspy** [wesbos/cobalt2-vscode#112]
Active indent guide is not visible when indent guide is rendered with `"editor.renderIndentGuides": true`. Currently using the following as a workaround:-

```json
"workbench.colorCustomizations": {
   "editorIndentGuide.activeBackground": "#ffc600"
}
```

**Comment by palashmon** [comment]
Thanks for reporting this issue. Could you please share some screenshots related to it, if possible? That would help us debug & fix this issue.

Regards!

**Comment by andrewspy** [comment]
This is the screenshot of with and without the active indent guide.

![cobalt2-without-active-indent-guide](https://user-images.githubusercontent.com/3106425/41708006-1741fe36-7572-11e8-8b61-7f96aa994252.JPG)

![cobalt2-active-indent-guide](https://user-images.githubusercontent.com/3106425/41708023-1b513fc8-7572-11e8-9d80-c0698b7a29c2.JPG)
