### ISSUE TITLE
Alternatives to using local settings file for vscode css

### ISSUE THREAD

**Issue by Ilrath** [wesbos/cobalt2-vscode#113]
Just food for thought, an alternative to using a local file would be to link the source to [your repo css file](https://raw.githubusercontent.com/wesbos/cobalt2-vscode/master/cobalt2-custom-hacks.css) or to instruct the user to create their own gist if they wish to customize it.

This has the added bonus of being cross platform and able to be combined with the 'Settings Sync' Extension

**Comment by palashmon** [comment]
Thanks. We are looking into it. Closing this issue for now.
