### ISSUE TITLE
Inconsistent syntax highlightning - .js, .jsx, .ts and .tsx

### ISSUE THREAD

**Issue by kristho91** [wesbos/cobalt2-vscode#114]
There is a inconsistent syntax highlightning.

*.js and *.jsx files seem pretty consistent, but *.ts and *.tsx are much different.

![js](https://user-images.githubusercontent.com/2781949/41996243-9696b474-7a54-11e8-9bcd-3264f531f929.png)
![jsx](https://user-images.githubusercontent.com/2781949/41996244-96aef0c0-7a54-11e8-88fa-dcdf9a90d7d0.png)
![ts](https://user-images.githubusercontent.com/2781949/41996245-96cfca70-7a54-11e8-9426-309e4060733b.png)
![tsx](https://user-images.githubusercontent.com/2781949/41996246-96ea6132-7a54-11e8-962b-3f97ff5920ad.png)

**Comment by LonghornRach** [comment]
Hi! I could look into this - is there a preference for one over the other?

**Comment by dzienisz** [comment]
`.js` looks the best for me

**Comment by larryranches** [comment]
Also seeing inconsistencies with .ts and .tsx files as mentioned above. Any traction on this?

**Comment by palashmon** [comment]
@LonghornRach Please go ahead and add a PR for this. The current colour code for js has a higher preference. The `*.ts` and `*.tsx` files need to be similar to `*.js` and `*.jsx` files. You can find the differences as shown in the images in OP.

Also, if anyone else is willing to take this, please go ahead.
