### ISSUE TITLE
Class names are Yellow and not purple like on Wes example

### ISSUE THREAD

**Issue by Runehm** [wesbos/cobalt2-vscode#118]
I have tried everything but i can't get the syntax to highlight in the right colours.

<img width="689" alt="skaermbillede 2018-08-10 kl 23 49 49" src="https://user-images.githubusercontent.com/11425087/43983004-b02557c6-9cf8-11e8-9f66-e175e89cf110.png">
<img width="1022" alt="skaermbillede 2018-08-10 kl 23 52 19" src="https://user-images.githubusercontent.com/11425087/43983005-b03eaa46-9cf8-11e8-903e-a615b842aa0b.png">

**Comment by Runehm** [comment]
Just bumping this ! Anyone having the same problem??

**Comment by MCrank** [comment]
Is that something you can override in your settings with the _editor.tokenColorCustomizations_?  Found this in the theme JSON that I believe is setting the color to the orange. (Disclaimer I am not familiar with this stuff at all so could be way offimpo)
```js
{
      "name": "Keyword",
      "scope": "keyword, storage.type.class",
      "settings": {
        "foreground": "#ff9d00"
  }
},
```

So you might try to add this to your editor: (Change the foreground to the color of purple you want)
```js
"editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": ["storage.type.class"],
        "settings": {
          "foreground": "#d166d2"
        }
      }
    ]
  }
```

This is what I get with that change if this is what you are looking for? (Bracket colors are from another extension (Bracket Pair Colorizer)


![tokencolor](https://user-images.githubusercontent.com/3493649/45265066-ae7f0500-b40b-11e8-9452-8684251b9204.PNG)

**Comment by palashmon** [comment]
Closing this issue for now, please reopen if that is not the case.

**Comment by jorge-ruvalcaba** [comment]
This just happened to me, the class names and function names are yellow by default. Should this be different?
