### ISSUE TITLE
Classes and Ids have same highliting in CSS

### ISSUE THREAD

**Issue by sebaslm** [wesbos/cobalt2-vscode#12]
I don't know if this is the intended behavior, but I do miss having different highlighting for classes and ids in CSS.

![screen shot 2017-09-13 at 23 06 40](https://user-images.githubusercontent.com/20850740/30379018-84027d10-98d8-11e7-8421-3662eceb6d9e.png)

**Comment by wesbos** [comment]
Nope- should look like this:

![](http://wes.io/mTxB/content)

**Comment by wesbos** [comment]
Fixed, also fixed the element selector colour

![](http://wes.io/mUPM/content)

**Comment by palashmon** [comment]
Next release is looking awesome already. Lots of bug-fixes and PR merged :tada:
