### ISSUE TITLE
The color of right click menu is too close to editor background in vscode 1.28 

### ISSUE THREAD

**Issue by V0idk** [wesbos/cobalt2-vscode#124]
![image](https://user-images.githubusercontent.com/17514799/46657039-f6977000-cbe1-11e8-8734-80eb3a3ba1c5.png)

**Comment by onetrev** [comment]
And the same applies to the drop down menus. Should that be a new issue or could it be hit up with this as it's essentially the same thing?

![capture](https://user-images.githubusercontent.com/597601/46715977-f5337980-ccad-11e8-8c86-4bcb3b683b36.PNG)

**Comment by V0idk** [comment]
> And the same applies to the drop down menus. Should that be a new issue or could it be hit up with this as it's essentially the same thing?
> 
> ![capture](https://user-images.githubusercontent.com/597601/46715977-f5337980-ccad-11e8-8c86-4bcb3b683b36.PNG)

i have post an new issue : https://github.com/Microsoft/vscode/issues/61105

**Comment by onetrev** [comment]
I personally think this should be left open, as a fix needs to be applied for all users, rather than something that relies on a style override.
