### ISSUE TITLE
Fonts do not work after macOS 10.14 update

### ISSUE THREAD

**Issue by msweett** [wesbos/cobalt2-vscode#125]
After updating to macOS Mojave (10.14) the fonts do not work. Uninstalling and re-installing the addon did not work.

VS Code version 1.28.1

**Comment by wesbos** [comment]
any font? Does it work with other themes?

**Comment by msweett** [comment]
Other themes/fonts don't seem to be working either, this probably isn't an addon-specific issue.

**Comment by msweett** [comment]
I found a fix for this issue from this article: https://ahmadawais.com/fix-macos-mojave-font-rendering-issue/

Run: `defaults write -g CGFontRenderingFontSmoothingDisabled -bool FALSE` and restart your computer.

**Comment by wesbos** [comment]
okay - better to open this with VS code then :)
