### ISSUE TITLE
Custom title bar style doesn't highlight options 

### ISSUE THREAD

**Issue by abibby** [wesbos/cobalt2-vscode#129]
In menus with window.titleBarStyle set to custom it doesn't highlight the selected item.

In each image, I am hovering over the "Open Workspace" option.

![native](https://user-images.githubusercontent.com/18175917/49701046-c6098d80-fbb4-11e8-85cd-89254c678f71.png)

![default-dark](https://user-images.githubusercontent.com/18175917/49701048-c99d1480-fbb4-11e8-8797-a5beb4c2d6bc.png)

![cobalt2](https://user-images.githubusercontent.com/18175917/49701050-cb66d800-fbb4-11e8-8cbc-0f17cb0937d0.png)

**Comment by wesbos** [comment]
fixed in 2.2.2
