### ISSUE TITLE
self not colored in argument of class method in Python

### ISSUE THREAD

**Issue by ajitid** [wesbos/cobalt2-vscode#13]
`self` inside method and in argument isn't colored same.
![screenshot from 2017-09-13 18-41-35](https://user-images.githubusercontent.com/26769888/30379360-d5898086-98b3-11e7-833c-00f62d7835b2.png)
![screenshot from 2017-09-13 18-41-51](https://user-images.githubusercontent.com/26769888/30379364-d841383c-98b3-11e7-8fab-e0f6ecfc7d7a.png)

**Comment by wesbos** [comment]
fixed! 

![](http://wes.io/mUIx/content)
