### ISSUE TITLE
Last typed character is red

### ISSUE THREAD

**Issue by anthonybarbatto** [wesbos/cobalt2-vscode#132]
Great theme. Can someone point me to the setting that is being used to turn the last typed character red? Thank you!

![graphql js momapi 2019-02-08 17-35-35](https://user-images.githubusercontent.com/744609/52514593-05118a80-2bc8-11e9-9a18-2ac302459137.jpg)

**Comment by wesbos** [comment]
this was vs code, should be fixed now
