### ISSUE TITLE
code highlighting for react fragments

### ISSUE THREAD

**Issue by theskillwithin** [wesbos/cobalt2-vscode#135]
code highlighting with react fragment sugar breaks the code highlighting on the rest of the page ie `<> ..... </>`

**Comment by theskillwithin** [comment]
=[

**Comment by wesbos** [comment]
I never had this issue - is it still an issue for you? Please re-open with screenshots and which highlighter you are using. Most language specific stuff is outside the scope of the theme

**Comment by theskillwithin** [comment]
This I think I finally figured out that a vscode babel plugin was causing the issue
