### ISSUE TITLE
VS Code status bar colors when debugger is active

### ISSUE THREAD

**Issue by InSuperposition** [wesbos/cobalt2-vscode#137]
![fofcontracts_js_—_Enogen](https://user-images.githubusercontent.com/433871/56911249-215bef80-6a72-11e9-8226-79b2197ceccc.jpg)
Status bar text color is hard to read.

While there is a PR that has been merged, I do not see the changes in the current version of this extension.
https://github.com/wesbos/cobalt2-vscode/issues/96
https://github.com/wesbos/cobalt2-vscode/pull/98

My workaround in the meantime:
```
 "workbench.colorCustomizations": {
    "[Cobalt2]": {
      "debugExceptionWidget.background": "#cc000069",
      "debugExceptionWidget.border": "#ff0000",
      "statusBar.background": "#0081c669",
      "statusBar.foreground": "#ffffffcc",
      "statusBar.debuggingBackground": "#00a6ff69",
      "statusBar.debuggingForeground": "#ff9d01ff"
    }
}
```

**Comment by sergio-domingues** [comment]
Would also like to see this fix in "production", it's a pain in the ass to have this contrast in debug mode

**Comment by wesbos** [comment]
sorry! deployed
