### ISSUE TITLE
Transparency in file explorer error/suggestion

### ISSUE THREAD

**Issue by ajitid** [wesbos/cobalt2-vscode#14]
![screenshot from 2017-09-13 18-40-03](https://user-images.githubusercontent.com/26769888/30379487-444c23b6-98b4-11e7-81d4-873bcd1561a2.png)

This info "A file or folder name must be provided" is transparent

**Comment by wesbos** [comment]
Hmm - do you know what this is called? I can't find it on this list:

https://code.visualstudio.com/docs/getstarted/theme-color-reference

**Comment by wesbos** [comment]
I don't think this is possible - feel free to re-open if you find it

**Comment by palashmon** [comment]
Found it:

![](https://code.visualstudio.com/images/theme-color-reference_input.png)

https://code.visualstudio.com/docs/getstarted/theme-color-reference#_input-control

Properties:-

```
inputValidation.errorBackground
inputValidation.errorBorder
```

**Comment by wesbos** [comment]
you rock!

**Comment by palashmon** [comment]
In case anyone wants to create a PR for this issue please add a comment here as "<code>In Progress</code>", so that anyone else also doesn't start working on the same issue. 

Thanks!

**Comment by wesbos** [comment]
fixed in the next release
