### ISSUE TITLE
Local development does not match current live version

### ISSUE THREAD

**Issue by salehmoh** [wesbos/cobalt2-vscode#142]
Hey, I tried looking around but may have missed it if it was mentioned already. I pulled down this project to create a PR of some changes that I thought would be helpful and it seems that this repo already has some of the changes I was looking to make. The live version of the theme still has the issues I'm trying to fix though. 

Some examples are:
- The status bar has a better appearance when running a debugging session.
  - Live version has a hard-to-see contrast on the status bar when debugging
- The terminal shows numbers better.
  - Live version shows numbers with almost the same color as the background so its very hard to see.
- The title bar menu at the top highlights options when hovering over them.
  - Live version has no "OnHover" color changes.

Does this repo's master branch match the current live version in the extensions marketplace? 
Or does the debugging instance of this project just appear to have some different appearance settings?

Note: The last updated date on Cobalt2 theme in the marketplace is on Feb 9, 2018. The last commit as of this issue is Mar 12, 2019.

**Comment by salehmoh** [comment]
I guess a better question is will the marketplace version ever get an update?

**Comment by chinwobble** [comment]
+1

**Comment by conradwt** [comment]
+1

**Comment by wesbos** [comment]
deplopyed!
