### ISSUE TITLE
Change Storage foreground

### ISSUE THREAD

**Issue by beltranrengifo** [wesbos/cobalt2-vscode#144]
I think is a good idea to change the color of Storage foreground, as it is simiar to function names.
Line 378:

```
{
      "name": "Storage",
      "scope": "storage",
      "settings": {
        "foreground": "#fb94ff"
      }
    },
```

**Comment by beckyw5** [comment]
Got this 👍

**Comment by dierubo** [comment]
Is this issue resolve? I'm very very interested

**Comment by arsari** [comment]
I suggest something similar, #153, , for the Select Language Mode in the Status bar. The snippet is for be insert in the .vscodestyle.css file

**Comment by wesbos** [comment]
Just rolled out a bunch of changes - should fix it for you!
