### ISSUE TITLE
powershell command line parameters contrast is too low

### ISSUE THREAD

**Issue by WiredSharp** [wesbos/cobalt2-vscode#146]
Hi,
i have a small issue when writing powershell commands as arguments are hard to distinguish from background as foreground color is blue and background dark blue.
Anyway, thank you for this great theme.

**Comment by palashmon** [comment]
Could you please share some images related to this issue? Thanks!

**Comment by fosztomatyas** [comment]
Same on cmd. 
![image](https://user-images.githubusercontent.com/32310039/65540533-46b33380-df14-11e9-8d99-8408641e67c4.png)

**Comment by AananthV** [comment]
Can I take this up? @palashmon 
@zericco 's issue seems to be caused by ```terminal.ansiBrightBlack``` which is set to ```#0050A4``` and doesn't provide enough contrast.
@fosztomatyas 's issue is different and is because ```terminal.ansiBrightWhite``` is set to ```#193549``` (which doesn't seem white at all)

**Comment by zericco** [comment]
@AananthV, you are right, the same issue apply with the default theme, contrast is not great either.

**Comment by gregid** [comment]
The same issue applies to `Jest` which also uses `terminal.ansiBrightWhite` to some of its output.
Until this is fixed - you can overwrite this with different color in your `settings.json`:
```
    "workbench.colorCustomizations": {
        "terminal.ansiBrightWhite": "#0088ff",
    },
```

**Comment by palashmon** [comment]
@AananthV yes, please feel free to create a PR. Thanks!

**Comment by MrSassyBritches** [comment]
![Annotation 2020-03-06 161204](https://user-images.githubusercontent.com/7945291/76129980-51471e00-5fc6-11ea-84bf-c0c444ed3344.png)
![Annotation 2020-03-06 161847](https://user-images.githubusercontent.com/7945291/76129981-51dfb480-5fc6-11ea-838d-9881d6f47aa3.png)
Hey, this worked great, thanks @gregid 
Before and after for anyone who wants to see

**Comment by wesbos** [comment]
fixed! Sorry folks
