### ISSUE TITLE
Increase minimap slider contrast to enhance its visibility

### ISSUE THREAD

**Issue by paulklemm** [wesbos/cobalt2-vscode#15]
The minimap slider is always visible in my settings.

```
"editor.minimap.showSlider": "always"
```

I find it hard to see because of the low contrast to the background 

![screen shot 2017-09-13 at 15 53 39](https://user-images.githubusercontent.com/2169489/30381197-fc0d8b52-989b-11e7-9115-d534580976da.png)

Here as comparison the minimap slider of the Material Theme where the slider is easily distinguishable from the background.

![screen shot 2017-09-13 at 16 00 37](https://user-images.githubusercontent.com/2169489/30381471-d37f8cf2-989c-11e7-852f-62b95dc97ad8.png)

I suggest increasing the contrast of the slider to enhance its visibility.

**Comment by wesbos** [comment]
thanks a lot - this was fixed when I fixed the scrollbar colours. Will be out in an hour or so.

![](http://wes.io/mTiH/content)
