### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by rachelholtz** [wesbos/cobalt2-vscode#150]
I have Operator Mono but all of the font's get's changed to it, not just the comments and a few React elements.

![Screen Shot 2019-10-15 at 10 40 15 AM](https://user-images.githubusercontent.com/23062081/66847042-584a9280-ef38-11e9-851a-9ef2b8be0815.png)

**Comment by wesbos** [comment]
You probably are explicitly using the italic weight as your editor font
