### ISSUE TITLE
python class name same as inherited class

### ISSUE THREAD

**Issue by yujinyuz** [wesbos/cobalt2-vscode#152]
Based on the screenshot, `MyDecimal` is the same with `Decimal`, but if we inherit from `object`, it gets a distinct color.

Wanted to fix the issue but I'm not sure how to create a scope selector for the inherited class

![code](https://user-images.githubusercontent.com/10972027/67531932-19b29600-f6f7-11e9-9f17-d73084136884.png)

**Comment by wesbos** [comment]
Hey - still an issue? Just rolled out a bunch of changes. please reopen if it is
