### ISSUE TITLE
CSS Color for Select Language Mode

### ISSUE THREAD

**Issue by arsari** [wesbos/cobalt2-vscode#153]
CSS property to color the Select Language Mode. This property needs to be added to the .vscodestyle.css file.

~~~ CSS
/* This change color to cyan for the select language mode */
#status\.editor\.mode {
  color: cyan !important;
  font-weight: 600;
}
~~~

**Comment by snehal2841** [comment]
Can I do this? Please elaborate how to do.

**Comment by arsari** [comment]
Hi. Just add the above CSS snippet in your .vscodestyle.css file and reload the file.
