### ISSUE TITLE
Your Code installation appears to be corrupt. Please reinstall.

### ISSUE THREAD

**Issue by jassem-lab** [wesbos/cobalt2-vscode#158]
about the CSS Hacks For Extra Sweet Editor
i maked the vscstyle.css
 "vscode_custom_css.imports": [
      "file:///C:/Users/jassem/.vscStylesheet.css"
    ],

**Comment by serhio-k** [comment]
You can go to https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css
and read SPECIAL NOTE directly on the top line

**Comment by wesbos** [comment]
The CSS Hacks are no longer needed -ill take them out
