### ISSUE TITLE
semantic highlighting in VSCode 1.43.0 breaks some colors

### ISSUE THREAD

**Issue by fritzfr** [wesbos/cobalt2-vscode#159]
Hey,

after the latest update (1.43.0), some colors are now white which were blue before, one example:

Before the Update:
![image](https://user-images.githubusercontent.com/49151885/76402921-63d5a480-6384-11ea-8f7f-b5e90e8e032f.png)

After the Update:
![image](https://user-images.githubusercontent.com/49151885/76402891-591b0f80-6384-11ea-8705-af192c8948af.png)

This can be "fixed" by setting: `"editor.semanticHighlighting.enabled": false`.
Seems like this theme would need some adjustments to reflect that new setting.

**Comment by wesbos** [comment]
Looks like VS code fixed this. please re-open if it's not the case
