### ISSUE TITLE
Multiple Selection on Words Highlight Color

### ISSUE THREAD

**Issue by pjlamb12** [wesbos/cobalt2-vscode#16]
When you select a word, it highlights all words on the page so you can see them. But then when you start selecting the other instances, there's no visible difference between the ones that have been selected and the ones that haven't been. See screenshot for example, hopefully that'll help it make more sense.

![screenshot](https://user-images.githubusercontent.com/2006222/30381536-eb57be3c-9859-11e7-89d6-a757a5cdca26.png)

As you can see, I've selected the first four (but you can only tell because of the caret next to them). It'd be nice if the selected ones looked different than the non-selected ones.

**Comment by wesbos** [comment]
Getting there but I can't for the life of me figure out how to style the additional selected items as the first one

![](http://wes.io/mUDo/content)

**Comment by wesbos** [comment]
Okay I'm not sure how to do the above, but at least this issue is fixed :)
