### ISSUE TITLE
Publish the theme on Open-vsx.org to allow VSCodium users to install it

### ISSUE THREAD

**Issue by GuimLe** [wesbos/cobalt2-vscode#163]
I love your theme but I can't use it in VSCodium now.

VSCodium now uses Open-vsx.org instead of MS Marketplace so we can't find this great theme on it.

I hope it won't be too hard to do but I really don't know.

**Comment by wesbos** [comment]
Requested it

**Comment by wesbos** [comment]
all good!

**Comment by GuimLe** [comment]
Great, thank you !
