### ISSUE TITLE
Change activity bar foreground color

### ISSUE THREAD

**Issue by ajitid** [wesbos/cobalt2-vscode#17]
Foreground color of activity bar is too bright

![30383651-cb0c1824-98bf-11e7-938d-6f33bd75d7bb](https://user-images.githubusercontent.com/26769888/30383882-5ca06e0c-98c0-11e7-8b10-66dffad5b5fd.png)

With `"activityBar.foreground": "#aaaaaa"` it aligns well with the theme.

![screenshot from 2017-09-13 20-13-02](https://user-images.githubusercontent.com/26769888/30383764-0b34b898-98c0-11e7-98f5-b0978fbd130c.png)

**Comment by wesbos** [comment]
Thanks fixed
