### ISSUE TITLE
Strange Colouring

### ISSUE THREAD

**Issue by nigelterry** [wesbos/cobalt2-vscode#173]
I just downloaded v2.2.3 and also enabled cobalt2-custom-hacks.css for the first time. When I look at my code in the editor, 
I see differing colours for three function definitions. See the attached file. const and the function names go

orange white
orange orange
white orange

Am I doing something wrong??

![Cobalt](https://user-images.githubusercontent.com/1019674/100487851-bacd0680-30d8-11eb-9dca-cb3fbf70c809.png)

**Comment by wesbos** [comment]
Hey! 

The first one is a variable, and correct. 

The second one is a variable with a function in it, correct. 

The third one is weird! I’ll have a look!

**Comment by nigelterry** [comment]
Maybe these will help:

![Screenshot_20201129_124938](https://user-images.githubusercontent.com/1019674/100549541-83c63480-3241-11eb-9f16-ded5812c2574.png)

![Screenshot_20201129_125324](https://user-images.githubusercontent.com/1019674/100549601-ed464300-3241-11eb-9a7f-3ca72ae455b7.png)

**Comment by wesbos** [comment]
can you paste this code you are using into the issue? It's breaking on some syntax highligting. 

Also, are you using `javascript` or `javascriptreact` for highligting?

**Comment by nigelterry** [comment]
Javascript React

File and settings.json in the archive. Let me know if you need anything else.

[Archive.zip](https://github.com/wesbos/cobalt2-vscode/files/5616739/Archive.zip)

**Comment by wesbos** [comment]
can you update to the latest (Update All Extensions in command palette). I'm not seeing this issue in any file..

**Comment by nigelterry** [comment]
Still the same issue with 2.2.5.

Is it related to the fact that BeersPage is the default export  from beers.js?

**Comment by Yasnohorodskyi** [comment]
![image](https://user-images.githubusercontent.com/62336521/124379008-40431580-dcbd-11eb-9738-56f24d3282fe.png)
Hi !  I am observing strange behaviour in the theme. CSS selectors go dark in one single file; others look good. Why it?

**Comment by aharvard** [comment]
> can you update to the latest (Update All Extensions in command palette). I'm not seeing this issue in any file..

Same. I'm not able to reproduce the issue. 

The settings provided in the zip did not set the .js file to be highlighted as `javascriptreact` by default for me. So, I manually switched between `javascript` and `javascriptreact` and both highlighted as expected (all `const`s yellow):

![image](https://user-images.githubusercontent.com/10472610/135719220-020d7597-b55a-408a-ba06-de0222f69c60.png)
