### ISSUE TITLE
[JavaScript] 2.2.XX not okay with objects

### ISSUE THREAD

**Issue by viclafouch** [wesbos/cobalt2-vscode#176]
I had to downgrade because the colors don't work for my JavaScript in the versions >= 2.0.0

Version 2.1.6
![image](https://user-images.githubusercontent.com/23353836/100606198-5d6bcc00-3309-11eb-95c0-89e71478b375.png)

Version 2.2.XX
![image](https://user-images.githubusercontent.com/23353836/100606460-c7847100-3309-11eb-9e9e-a88a723d2bae.png)

The keys of an object have the same color as the values, and this is very disturbing.

Am I the only one ? I tried to redownload VS Code, clear cache, etc... nothing changes.

**Comment by wesbos** [comment]
Thanks for the report! Will get this fixed

**Comment by wesbos** [comment]
fixed, will push a release in 20 mins
