### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by jefflindholm** [wesbos/cobalt2-vscode#177]
Not really an issue, but you could include 2 other font options for folks - Dank Mono (still costs but lots less than 200), or Victor Mono (free OS font)

**Comment by wesbos** [comment]
Hey! You can use whatever font you want in this theme. It's not limited to just Operator Mono. Or am I misunderstanding your request?

**Comment by jefflindholm** [comment]
Was just saying 2 more cursive fonts to add if people like the look but not the ($200) :)

**Comment by wesbos** [comment]
Oh in the settings? I can add those!

**Comment by wesbos** [comment]
https://github.com/wesbos/cobalt2-vscode/commit/cd0090d0f6e29722b567f6df4d913c917f2b58d4

**Comment by wesbos** [comment]
done!
