### ISSUE TITLE
Scroll bar color

### ISSUE THREAD

**Issue by AlexSZYDLO** [wesbos/cobalt2-vscode#184]
Hi,
I've been using this theme for a long time already and I love it except just one little thing: the scrollbar color.
I think it's too similar to the editor background color, and often when I want to grab the scroll bar to go up or down my file, I need to search it. It gets especially annoying with huge file because the scroll bar is small (and I personally use the scroll bar mostly with large files). See screenshot below, it's very hard to see the scroll bar.
The color when it's hover is fine in my opinion, I think that should be the default color.
It's also not easy to see the current location in the minimap.

Thanks a lot,
Alexandre

![image](https://user-images.githubusercontent.com/29868175/109653238-10460300-7b61-11eb-8375-632e8749e818.png)

**Comment by Mfonn** [comment]
Hi Can I be assigned this issue @emzoumpo

**Comment by palashmon** [comment]
Fixed in PR #210
