### ISSUE TITLE
GitLens hover colors

### ISSUE THREAD

**Issue by kingcard1131** [wesbos/cobalt2-vscode#185]
I use cobalt2 theme and gitlens extension, how can i change this hover text‘s colors?’ something like this below
![issue](https://user-images.githubusercontent.com/53737003/113415733-6b824400-93f2-11eb-8fce-da42898ad141.jpg)

when I used other themes，the gitlens hover text color like this(I want this colors)：the text which is deleted is RED and which is added is green!
![issue1](https://user-images.githubusercontent.com/53737003/113416115-30ccdb80-93f3-11eb-9b33-7d6a12663dfa.jpg)

Thank you very much for your job!

**Comment by aharvard** [comment]
Hey @kingcard1131, I just opened a PR to address this issue. Hope it meets your needs!

**Comment by palashmon** [comment]
Fixed in PR #199
