### ISSUE TITLE
CSS selectors go dark in one single file

### ISSUE THREAD

**Issue by Yasnohorodskyi** [wesbos/cobalt2-vscode#191]
image
Hi ! I am observing strange behaviour in the theme. CSS selectors go dark in one single file; others look good. Why it?
![image](https://user-images.githubusercontent.com/62336521/124379594-a67d6780-dcc0-11eb-826c-be8e46eccd8f.png)

**Comment by aharvard** [comment]
Hey @Yasnohorodskyi, I have a few questions
1. Are you on the latest version of the theme (`v2.2.5`)?
1. Does this happen in a file that ends in `.css`?
2. When the files is open, what associate does it have? Do you see "CSS" in the VS Code bottom bar?  ![image](https://user-images.githubusercontent.com/10472610/135719810-f0321ece-5632-46b4-8db7-c775256bb8aa.png)
3. Can you post a screenshot of your selector's tokens and scope? Follow these steps:
a. place your cursor in inside of the css selector
b. select `Developer: Inspect Editor Tokens and Scopes` via the command pallet (`cmd` + `shift` + `p` ...or `ctrl` + `shift` + `p` for windows) 
c. take screenshot (should look like this) 
![image](https://user-images.githubusercontent.com/10472610/135720044-26c3140d-a84f-4226-a578-651dbc913597.png)
