### ISSUE TITLE
Console cursor and text color are equals

### ISSUE THREAD

**Issue by GonzaloArielRossi** [wesbos/cobalt2-vscode#200]
Hi! This is my first time reporting an issue, so excuse me in advance if I do something wrong.

I have a problem in the terminal. The cursor is solid yellow and the text is yellow too. So, when the cursor is over some text, you can't see it.
![vscode_theme_issue](https://user-images.githubusercontent.com/52679082/139142555-89970abb-8198-43ed-b11c-3d83048bd9ed.png)

**Comment by EthicalChaos** [comment]
This should fix it!
