### ISSUE TITLE
How to remove italics?

### ISSUE THREAD

**Issue by bmarvinb** [wesbos/cobalt2-vscode#207]
Is it possible to remove italics completely?
<img width="308" alt="CleanShot 2022-07-28 at 22 01 20@2x" src="https://user-images.githubusercontent.com/23120972/181616986-be2937be-ad8c-43db-a2f0-e55815fdf38f.png">
For example, remove italics from type?

**Comment by Nikhil562** [comment]
I would love to do that , can you please assign it to me

**Comment by Eitheages** [comment]
Hello @bmarvinb, you can add these lines in your settings:
```json
"editor.semanticTokenColorCustomizations": {
    "rules": {
        "interface.declaration": {
            "fontStyle": ""
        }
    }
}
```

Pardon me @SmitAkbari26 cuz I suggest not modify commit the change globally. Some developers may be used to the italic form.

**Comment by SmitAkbari26** [comment]
@Eitheages  I got it.

**Comment by palashmon** [comment]
Closing this issue for now, as it seems to be resolved based on @Eitheages comment above.
Thank you!
