### ISSUE TITLE
[php] variable colours

### ISSUE THREAD

**Issue by Mikeysauce** [wesbos/cobalt2-vscode#21]
Hey Wes,

I like the look of this theme, but feel perhaps the variables in PHP could use a little bit of colour. Below is the theme I was using compared to cobalt.

Cobalt
![image](https://user-images.githubusercontent.com/1942799/30387655-1b18ffe6-98a5-11e7-8d16-33b5aeab23ea.png)

Other
![image](https://user-images.githubusercontent.com/1942799/30387628-fd5eb270-98a4-11e7-9532-71438a7dc330.png)

**Comment by wesbos** [comment]
Fixed! It will be out soon! 

![](http://wes.io/mTiE/content)
