### ISSUE TITLE
Customize the color of specific object types in python

### ISSUE THREAD

**Issue by GitHunter0** [wesbos/cobalt2-vscode#218]
Hey @wsantos , first congratulations for this great theme.

I'm using python, and there are some objects that should ideally get different colors. 
Please consider the example below: 
![image](https://user-images.githubusercontent.com/26294221/210013451-37342d37-8168-4369-be8a-a2d801cf496f.png)

 `d` (inside the function), `sum` and `df` are getting the same blue color despite being of different types.

Is there a way that I could myself customize those colors? 

I tried `"editor.tokenColorCustomizations"` configuration, it was able to change the color of other objects but not those I mentioned above.

Thank you

**Comment by wsantos** [comment]
Hey @GitHunter0, @wesbos is the owner, not me I'm just a contributor :D, kudos to him.

**Comment by wesbos** [comment]
thanks for this. I'm not a python Dev so ill have to ask someone who knows the language to contribute those

**Comment by palashmon** [comment]
This should be resolved now in PR #223
