### ISSUE TITLE
Debug console error color

### ISSUE THREAD

**Issue by mikij** [wesbos/cobalt2-vscode#234]
![image](https://github.com/wesbos/cobalt2-vscode/assets/4502100/5b11fcf4-8506-401a-93c9-1cb08aa5834d)

As you can see on the posted image, error color is to dark on the dark background so it is really hard to read text there. Please set some lighter red color so we can read error text easier. Thank you.

**Comment by Eitheages** [comment]
Are you sure the color is provided by the theme, rather than the debugger itself?

I have no idea to reproduce it in my working environment. Could you plz show some code snippets?

**Comment by mikij** [comment]
Well if I change color theme the colors are different in DEBUG console window. What code snippet do you ask? This happens when I debug in browser and then some error message occurs.

**Comment by mikij** [comment]
this is even more accurate how it looks like because previous screenshot wah taken with mouse hovering the error area
<img width="441" alt="image" src="https://github.com/wesbos/cobalt2-vscode/assets/4502100/8da80a9e-348e-4a05-93db-31511658a0d1">

**Comment by wesbos** [comment]
Yeah this is our red, which I agree doesn't look good in the debug console - should be fixed. I wonder if we can just change the red there - as I like the red when it's on the lighter editor background blue.

Anyone want to take this on?

**Comment by rennsax** [comment]
> What code snippet do you ask? This happens when I debug in browser and then some error message occurs.

@mikij Hello I mean how to reproduce the color with minimal codes. I rarely met it before.

**Comment by rennsax** [comment]
@wesbos The red should be lighter as the background is very dark blue. I may take this on later.

**Comment by mikij** [comment]
> > What code snippet do you ask? This happens when I debug in browser and then some error message occurs.
> 
> @mikij Hello I mean how to reproduce the color with minimal codes. I rarely met it before.

Well, run and debug any application. You can put console.error('something to print') and you will see this text in red as a result in the debug console

**Comment by mikij** [comment]
and putting this in my settings JSON also overwrites what we have right now
`"workbench.colorCustomizations": {
    "debugConsole.errorForeground": "#ff5630"
  }`

**Comment by rennsax** [comment]
@mikij You can close the issue as it has been fixed via PR #237.

**Comment by wesbos** [comment]
thanks a million folks - really appreciate the help on this
