### ISSUE TITLE
Background color for selected text in sidebar and search

### ISSUE THREAD

**Issue by corydeppen** [wesbos/cobalt2-vscode#24]
Have you considered changing the background color for selected text in areas like the side bar, find panel, and search box? The dark on slightly lighter background can be tricky to see.

![cobalt2-filename-bg](https://user-images.githubusercontent.com/313264/30400135-ebe3110e-98a3-11e7-86a7-20434726981b.png)

![cobalt2-file-search-bg](https://user-images.githubusercontent.com/313264/30400179-06e6d7f6-98a4-11e7-8b73-332b1ef4b5e6.png)

![cobalt2-sidebar-search-bg](https://user-images.githubusercontent.com/313264/30400136-ebe3b956-98a3-11e7-9ebb-d9eaaba50221.png)

Thanks for your work on this - it looks great so far.

**Comment by corydeppen** [comment]
What are your thoughts on changing `selection.background` to `#ffc60033` to be consistent with `editor.hoverHighlightBackground`?

**Comment by wesbos** [comment]
Thansk Cory - I'm a bit confused over all the higihlight colours available so I was having trouble getting it all owrking. Will give it another crack tomorrow.

**Comment by wesbos** [comment]
This will be changed to match the editor selection:

![](http://wes.io/mWPG/content)
