### ISSUE TITLE
Selecting Text From Search

### ISSUE THREAD

**Issue by CaleCrawford** [wesbos/cobalt2-vscode#25]
Similar to #23.

When I search for `node` in my package.json file and then try to highlight this string it looks like the 'node' portion of the string is not highlighted.
Example:
http://typenine.d.pr/6fb4J/1NolJIhL

**Comment by palashmon** [comment]
In case anyone wants to create a PR for this issue please add a comment here as "<code>In Progress</code>", so that anyone else also doesn't start working on the same issue. 

Thanks!

**Comment by wesbos** [comment]
Okay - so there is a bit of theme limitation here so I'm switching to what chrome does for matching. Orange for current instance and yellow for additional instances 

![](http://wes.io/mVRD/content)

**Comment by wesbos** [comment]
![](http://wes.io/mW2s/content)
