### ISSUE TITLE
Scrollbar is hiding cursor position and warnings/errors

### ISSUE THREAD

**Issue by ajitid** [wesbos/cobalt2-vscode#26]
Scrollbar has no transparency, and so is hiding cursor position and any warning/error

Scrollbar hiding cursor and warning

![screenshot from 2017-09-14 18-07-20](https://user-images.githubusercontent.com/26769888/30430130-d51f8da6-9977-11e7-8e56-102f384d8597.png)

Scrollbar showing cursor (yellow) and warning (green) in itself when scrolled out

![screenshot from 2017-09-14 18-04-44](https://user-images.githubusercontent.com/26769888/30430179-05e2863c-9978-11e7-9257-0fd1107bfba5.png)

**Comment by wesbos** [comment]
Oh! good call - thank you

**Comment by wesbos** [comment]
fixed in the next rlsssss
