### ISSUE TITLE
Activity Bar notification getting clipped along bottom

### ISSUE THREAD

**Issue by josephfusco** [wesbos/cobalt2-vscode#27]
![screen shot 2017-09-14 at 10 37 18](https://user-images.githubusercontent.com/6676674/30435927-f7a80522-9938-11e7-9e3b-a1216be5ff96.png)

--------
BTW great work on this port! I was originally using this when I made the switch to VS Code, but switched over to some 'unofficial' version because they had the file tree and menu styles. Just switched back to this and it's 🔥

**Comment by wesbos** [comment]
Are you changing the font at all or just using the default one?

**Comment by josephfusco** [comment]
Using Operator Mono & vscode custom css containing just https://github.com/wesbos/cobalt2-vscode/blob/master/cobalt2-custom-hacks.css

**Comment by wesbos** [comment]
@josephfusco Can you try this before I comit it? 

```
.monaco-workbench>.activitybar>.content .monaco-action-bar .badge .badge-content {
  top: 17px;
}
```

**Comment by josephfusco** [comment]
Negative.

I just went into developer tools and changed the same thing from `top: 20px` to `top: 17px`, however it doesn't seem to stick in the custom css file, even with `!important`. 🤔

**Comment by josephfusco** [comment]
I would say go for it. Seems like I just have the custom css bit configured incorrectly right now.

**Comment by wesbos** [comment]
You have to reload the css via the command palette - did you do that?

**Comment by josephfusco** [comment]
That was it! Thanks!

**Comment by wesbos** [comment]
Fixed -thanks!
