### ISSUE TITLE
Error Messages should have a border

### ISSUE THREAD

**Issue by wesbos** [wesbos/cobalt2-vscode#28]
They kind of blend in right now and I missed a few of them.

![](http://wes.io/mWp4/content)

**Comment by ajitid** [comment]
![image](https://user-images.githubusercontent.com/26769888/30452632-07052560-99b4-11e7-8d8c-d1324b4574e4.png)
totally unrelated to the issue but that "error" label and button can be styled too

**Comment by wesbos** [comment]
too bad there isn't a border property. Will switch it to yellow
