### ISSUE TITLE
Split window needs a clear border, or a darker background for the gutter.

### ISSUE THREAD

**Issue by jordandrako** [wesbos/cobalt2-vscode#30]
When using a split editor it's difficult to see the separation, especially in the settings editor. Could we get a darker gutter or a thicker border?

![image](https://user-images.githubusercontent.com/7110658/30441855-d9c68142-9937-11e7-841e-f7216b7d29f1.png)

**Comment by wesbos** [comment]
Good call! Fixed in the next release. 

![](http://wes.io/mX10/content)
