### ISSUE TITLE
Color in the function name

### ISSUE THREAD

**Issue by jousmo** [wesbos/cobalt2-vscode#34]
Hi Wes, it is correct that the color of the name of the function is equal to its declaration.

<img width="341" alt="captura de pantalla 2017-09-15 a la s 08 32 37" src="https://user-images.githubusercontent.com/7170689/30484831-41395e44-99f1-11e7-9893-d5aba1262be7.png">

**Comment by wesbos** [comment]
This is the correct colour for method and functions - it it is the same colour as the variable declaration keyword though - could be changed..

**Comment by jousmo** [comment]
Thank you Wes, I thought it was not right.

**Comment by AiaRup** [comment]
Hi, is there a way to change the color of var and let in those cases?
It's a little disturbing that the color is the same,
Any help will be appreciated!
