### ISSUE TITLE
Crash VSCODE

### ISSUE THREAD

**Issue by jousmo** [wesbos/cobalt2-vscode#35]
Hi, Wes. update cobal2 and when you enable CSS from command palette, vscode is broken.

<img width="1218" alt="captura de pantalla 2017-09-15 a la s 10 56 05" src="https://user-images.githubusercontent.com/7170689/30492185-466fa8e6-9a05-11e7-8c73-9a77f72521c1.png">

"vscode_custom_css.imports": [
    "/Volumes/Macintosh HD/Users/Jousmo/.vscodestyles.css"
]

![captura de pantalla 2017-09-15 a la s 11 03 14](https://user-images.githubusercontent.com/7170689/30492264-832df684-9a05-11e7-9a7a-d92613ecff7e.png)

**Comment by plambhsa** [comment]
This is a result of using the custom CSS and JS plugin. If it doesn't work for you, disable the custom CSS and JS from the command palette and then disable the plugin.

**Comment by wesbos** [comment]
Yeah I have this too - it's part of the install steps of the custom plugin. 

Apparently there is another plugin which will hide that part in the title bar - haven't looked into it yet. 

If you ignore that warning forever it will work no problem
