### ISSUE TITLE
Invalid Syntax Color

### ISSUE THREAD

**Issue by abdelrahmanrifai** [wesbos/cobalt2-vscode#36]
Invalid syntax color is annoying and hard for the eye.

![screen shot 2017-09-15 at 8 46 10 pm](https://user-images.githubusercontent.com/4334778/30499288-9264094c-9a62-11e7-9cd1-d3f8c7bf95bf.png)

**Comment by wesbos** [comment]
Hmmmmm you are right - I had changed the red so the rest of the app looks good but I guess it uses this as well. Will revert

**Comment by abdelrahmanrifai** [comment]
I tried to fix it by changing it to be a background color instead of foreground, however I couldn't due to: https://github.com/Microsoft/vscode/issues/3429 😬

**Comment by abdelrahmanrifai** [comment]
I decided to hack into it via the custom-hacks.css file!👇
![cobalt2-css](https://user-images.githubusercontent.com/4334778/30501487-60ef0d5e-9a6b-11e7-9bc1-7dfd354c14f8.png)
Should I create a pull request or do you have another solution? 🤔

**Comment by wesbos** [comment]
Looks good but I don't want to rely on the CSS hacks as not everyone will install those :\

**Comment by wesbos** [comment]
Fixing this by making invalid a ligher red

![](http://wes.io/pRJa/content)
