### ISSUE TITLE
Stylus syntax support

### ISSUE THREAD

**Issue by yannick1691** [wesbos/cobalt2-vscode#39]
Dear Wes,

There is a plugin called language-stylus which add syntax support for Stylus in VScode.
However when using that with cobalt 2 almost all text will be green. 

i added support for stylus syntax in cobalt 2 by adding source.stylus (then the property name u defined) every time you used source.css 

This adds full proper syntax support to stylus with Cobalt2.

i have attached the before and after screenshots and the edited cobalt2.json

Withouth support.stylus added:
![withouth-sourcestylus](https://user-images.githubusercontent.com/19853448/30520319-86c13624-9bab-11e7-9122-88d39ae33b97.png)

With support.stylus added:
![with-sourcestylus](https://user-images.githubusercontent.com/19853448/30520322-8b7ab604-9bab-11e7-8655-761f1a4ac474.png)

Added support.stylus to cobalt2.json:
[cobalt2-with-stylus.zip](https://github.com/wesbos/cobalt2-vscode/files/1309036/cobalt2-with-stylus.zip)

**Comment by wesbos** [comment]
thanks - any way you could submit a Pull Request with this change?

**Comment by yannick1691** [comment]
Have made a pull request to add Stylus support. #46
