### ISSUE TITLE
Expand selection doesn't work well with quotes

### ISSUE THREAD

**Issue by ajitid** [wesbos/cobalt2-vscode#4]
![peek 2017-09-13 06-27](https://user-images.githubusercontent.com/26769888/30354926-72669cd4-984d-11e7-9e71-4fe50f6c2369.gif)

Ideal behaviour would be to not include quotes.

![peek 2017-09-13 06-29](https://user-images.githubusercontent.com/26769888/30354934-8369d348-984d-11e7-96fb-79f73439226f.gif)

If quotes and text have have same color, it includes quotes in the selection else it doesn't.

**Comment by ajitid** [comment]
Unlike screenshots, I am not getting thick caret in Ubuntu. Do I need to install vscode-custom-css manually (maybe Cobalt2 is not installing it as a dependency) and perform steps given in its instruction or is there any other problem?

**Comment by wesbos** [comment]
Interesting! So because they are the same colour it includes them in the expand - let me try change their colour

**Comment by wesbos** [comment]
Fixed! Will be out soon
