### ISSUE TITLE
color highlight

### ISSUE THREAD

**Issue by marekzelinka** [wesbos/cobalt2-vscode#40]
Is there a setting to display color highlight inline as a background color, like you have? Thanks.

![Image of VsCode Editor](https://raw.githubusercontent.com/wesbos/cobalt2-vscode/cobalt2-updates/images/ss.png)

Mine is like this: 
![Image of VsCode Editor](https://www.dropbox.com/s/f0hz0cymq3q7zbs/Sn%C3%ADmka.PNG?raw=1)

**Comment by wesbos** [comment]
Yep - I installed this plugin:

https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight

And disabled the built in one:

  "editor.colorDecorators": false,
