### ISSUE TITLE
find & replace: case sensitive, whole word, regex buttons selection state hard to see

### ISSUE THREAD

**Issue by blacktop** [wesbos/cobalt2-vscode#42]
![screen shot 2017-09-17 at 10 36 07 am](https://user-images.githubusercontent.com/6118188/30522886-80b7707a-9b94-11e7-98a4-0da593b6334e.png)

It is almost indistinguishable between selected or not.

Slightly brighter grey text color and a VERY faint box around the button when selected.

Thanks!

**Comment by wesbos** [comment]
Good call - will fix this. Thank you!

**Comment by wesbos** [comment]
fixed in the next relase
