### ISSUE TITLE
Find all references panel blend-in into code

### ISSUE THREAD

**Issue by ppasieka** [wesbos/cobalt2-vscode#43]
**Find All References Panel** - is hard to see where panel starts and where it ends.
(Right click on some variable and then select 'Find all references')

![image](https://user-images.githubusercontent.com/2170707/30531540-521b56a8-9c4f-11e7-9bb0-e9d60d246910.png)

**Comment by wesbos** [comment]
thanks a ton - will take a look at this!

**Comment by wesbos** [comment]
This is fixed in the next release

![](http://wes.io/pQJI/content)
