### ISSUE TITLE
Built in terminal single letter flag color is black/unreadable

### ISSUE THREAD

**Issue by micahgodbolt** [wesbos/cobalt2-vscode#44]
![image](https://user-images.githubusercontent.com/1434956/30553350-d96ee556-9c55-11e7-977c-e223299984da.png)

**Comment by micahgodbolt** [comment]
there's really a -m there

**Comment by micahgodbolt** [comment]
single '-' character is also black

**Comment by alisdairb1995** [comment]
I have discovered that this seems to be an issue with CMD or Power shell on windows having come across this on my work PC in a few areas predominately command line parameters. However on a mac running the latest VS Code and Cobalt2 version command line parameters appear fine.

Hopefully this information is helpful, will try to look myself at a fix this coming week.

**Comment by wesbos** [comment]
thanks again!

**Comment by wesbos** [comment]
(will cut a release soon)
