### ISSUE TITLE
Version control merge conflict highlighting is gone.

### ISSUE THREAD

**Issue by noeladd** [wesbos/cobalt2-vscode#45]
I frequently use vscode's version control tab to resolve merge conflicts. Since this theme was updated last week the merge conflict highlighting is not working. 

This is the merge conflict interface with the extension turned off: 
<img width="789" alt="screen shot 2017-09-18 at 4 26 40 pm" src="https://user-images.githubusercontent.com/8063846/30562941-3140a41c-9c8e-11e7-89f2-d570622f94d6.png">

This is with it turned on: 
<img width="778" alt="screen shot 2017-09-18 at 4 26 20 pm" src="https://user-images.githubusercontent.com/8063846/30562954-375f4d12-9c8e-11e7-9846-7bc25ce20770.png">

I'm loving this theme but I'm not liking what it's doing to the merge conflict markers

**Comment by wesbos** [comment]
thanks! will fix this

**Comment by wesbos** [comment]
If anyone wants to submit a PR to this I'd love it :)

**Comment by ayodeleopetumo** [comment]
Hi Wes,

Submitted a PR for this issue #88

**Comment by lamartire** [comment]
@wesbos how about merge #88? I really miss that :cry:

**Comment by palashmon** [comment]
Hi @wesbos, I think this issue can be closed now as PR #88 was merged.

Regards!

**Comment by lamartire** [comment]
@wesbos hm, the problem appeared again. Using v2.1.6 🤔

**Comment by tomevans18** [comment]
+1 issue is back.

**Comment by danielnieto** [comment]
guess who's back? back again, issue is back, tell a friend

**Comment by react-native-guy** [comment]
Hi @wesbos , I can confirm that the latest version has this bug. Can you verify and reopen this issue ?

**Comment by rlynn523** [comment]
Agree with @JoaoFGuiomar. I noticed that it is present in the source code, but still not included in the published version in the marketplace. I ended up just editing the cobalt2.json myself, but would love to see it back in the published version. If there is something I can do to help, please let me know!

**Comment by ItamarShDev** [comment]
@wesbos can you please publish the latest version with the conflicts coloring?

**Comment by ItamarShDev** [comment]
@rlynn523 the same code is in the package , but not working for some reason
