### ISSUE TITLE
Workbench badge count is not visually circular

### ISSUE THREAD

**Issue by josephfusco** [wesbos/cobalt2-vscode#47]
Using your recommended custom CSS with Operator Mono.

![screen shot 2017-09-19 at 10 20 14](https://user-images.githubusercontent.com/6676674/30597397-df0bb47e-9d24-11e7-8bbe-a42106566026.png)

This seems to do the trick although I haven't tested it thoroughly.

```
.monaco-count-badge {
    padding: .2em .6em;
}
```

**Comment by wesbos** [comment]
I think this is impossible to fix because everyone is using different fonts that have different heights to them.  I already fixed it for another font, but then this one breaks. Feel free to reopen if you think you have a solution :)
