### ISSUE TITLE
Discrepancies between Sublime and VSCode syntax coloring

### ISSUE THREAD

**Issue by pmbaumgartner** [wesbos/cobalt2-vscode#48]
Thanks to everyone who has contributed to this awesome theme and the VSCode version. 

I'm noticing some small differences between Sublime and VSCode when using the theme. I'm not fluent in how the themes are constructed, so I'm not sure which ones are just a result of differences in themeing options or syntax highlighting between the two. 

Here's a few examples:

JS - (sublime on left, vscode on right)
![screen shot 2017-09-20 at 1 40 07 pm 2](https://user-images.githubusercontent.com/5107405/30659075-b9de76e6-9e0a-11e7-865f-829e14aea5b2.png)

Differences:
- Base color is different -- light grey in Sublime, white in VSCode
- Quoted Strings are dark green in Sublime, mint in VSCode
- Function call inside of a function is not highligted in Sublime and highlighted in VSCode (call to `peep()` inside the `peep()` function

I code mainly in python, so here's an example comparison: 
![screen shot 2017-09-20 at 1 40 37 pm 2](https://user-images.githubusercontent.com/5107405/30659238-41867a58-9e0b-11e7-91c0-741b08ae2754.png)

Differences:
- docstrings are blue in Sublime, mint in VSCode
- certain references are light blue in VSCode where nothing has that color in Sublime (lines 699 and 716 have examples)
- certain references are pale yellow in Sublime and white or light blue in VSCode (lines 697, 699, and 716)
- quoted strings are dark green in Sublime, mint in VSCode

---

I'm happy to help fix, but I think it would be helpful for someone with more experience to determine which of these differences are due to differences in how Sublime and VSCode themes work and which ones are just things that haven't been ported yet.

**Comment by kleinfreund** [comment]
Overall, the VSCode theme has a better contrast which might be an important factor for some people. I prefer it.

**Comment by wesbos** [comment]
Thanks - I tihnk the additions to the VS Code highlighting is better - please do feel free to submit PRs for anything that is broken though
