### ISSUE TITLE
Freemarker theme is confusing

### ISSUE THREAD

**Issue by jazzninja** [wesbos/cobalt2-vscode#50]
The color scheme when working in a Freemarker file (.ftl) is very hard to read. Functions and statements come through as a readable color, but everything else (variables, parameters, etc) are all white and blend together. The Monokai Dark theme seems to have a readable color scheme for these files, is this something that can be implemented? Thanks Wes!

**Comment by wesbos** [comment]
Can you post an example? I've never worked with that before
