### ISSUE TITLE
Having trouble with custom css

### ISSUE THREAD

**Issue by jakerohr** [wesbos/cobalt2-vscode#51]
I can't figure out why the custom css is not working (I can tell because the cursor hack is not overwriting the underline-thin setting) 
I've followed these steps: 

1. installed the vscode-custom-css plugin
2. copied the css into `vscodestyles.css` and set `vscode_custom_css.imports` to the file path
3. enabled Custom CSS and JS form the command palate
4. restarted vs code

Still no change to the cursor

I noticed this in the custom-css plugin documentation:
`IMPORTANT: Items in “vscode_custom_css.imports” should be URLs, instead of file paths. For local files, prefix it with “file://”.`

I tried prefixing with `"file://"` but that didn't work either. I even tried linking to Wes' css on github in my settings to no avail:

![screen shot 2017-09-21 at 1 29 09 pm](https://user-images.githubusercontent.com/10217510/30717183-eeb4e83e-9ed0-11e7-9799-36f1a53393a7.png)

What am I missing?

**Comment by abdelrahmanrifai** [comment]
You've to use a local file to get it work.

Where did you save your local file, and what's the file path you were using?

Also you may select _Help > Toggle Developer Tools_ and check the console for any errors.

**Comment by wesbos** [comment]
Yep - check the readme for updated instructions
