### ISSUE TITLE
Where am I going wrong with custom CSS import?

### ISSUE THREAD

**Issue by squaredindex** [wesbos/cobalt2-vscode#54]
I can figure out where I'm going wrong with importing my custom CSS, am I just formatting the path incorrectly? Also tried putting the file in root as suggested `~/.vscodestyles.css` and also adding `file://` but just don't seem to be able to make any changes via the CSS file.

Probably being a big noob and missing something obvious but it's driving me nuts.

```
{
  "workbench.colorTheme": "Cobalt2",
  "editor.fontFamily": "Operator Mono, Menlo, Monaco, 'Courier New', monospace",
  "editor.fontSize": 17,
  "editor.lineHeight": 25,
  "editor.letterSpacing": 0.5,
  "files.trimTrailingWhitespace": true,
  "editor.fontWeight": "400",
  "prettier.eslintIntegration": true,
  // this isn't really underline-thin but we hack it to be a thicker cursor
  "editor.cursorStyle": "underline-thin",
  "editor.cursorBlinking": "solid",
  // Very important: Install this plugin: https://github.com/be5invis/vscode-custom-css
  // you'll need to change this to an absolute path on your computer
  "vscode_custom_css.imports": [
    "/Volumes/Macintosh HD/Users/lev/.vscodestyles.css"
  ],
  "editor.renderWhitespace": "all"
}
```

**Comment by jastuccio** [comment]
```
"vscode_custom_css.imports": [
    "/Volumes/Macintosh HD/Users/lev/.vscodestyles.css"
```

"Macintosh HD" is not the correct path name on my machine.  Maybe your HD is named something different?

I can get to the .vscodestyles.css file typing the path into terminal, but am still having issues with custom css.  I tried adding `file://` too

**Comment by squaredindex** [comment]
Thanks for the response. Macintosh HD is definitely right for my machine, like you can I can reach via terminal.

**Comment by jastuccio** [comment]
From issue #51 "Having trouble with custom css"   select `Help > Toggle Developer Tools `and check the console for any errors.

```
Failed to load resource: net::ERR_FILE_NOT_FOUND  /Volumes/Macintosh%20HD/Users/joe/.vscodestyles.css
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 [/Users/joe/.vscode/extensions/thekalinga.bootstrap4-vscode-2.4.0]: Unknown language in `contributes.snippets.language`. Provided value: blade
e._logMessageInConsole @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 [/Users/joe/.vscode/extensions/thekalinga.bootstrap4-vscode-2.4.0]: Unknown language in `contributes.snippets.language`. Provided value: ejs
e._logMessageInConsole @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 [/Users/joe/.vscode/extensions/thekalinga.bootstrap4-vscode-2.4.0]: Unknown language in `contributes.snippets.language`. Provided value: latte
e._logMessageInConsole @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 [/Users/joe/.vscode/extensions/thekalinga.bootstrap4-vscode-2.4.0]: Unknown language in `contributes.snippets.language`. Provided value: tpl
e._logMessageInConsole @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 [/Users/joe/.vscode/extensions/thekalinga.bootstrap4-vscode-2.4.0]: Unknown language in `contributes.snippets.language`. Provided value: twig
e._logMessageInConsole @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 [/Users/joe/.vscode/extensions/thekalinga.bootstrap4-vscode-2.4.0]: Unknown language in `contributes.snippets.language`. Provided value: vue
e._logMessageInConsole @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28 [Extension Host] vscode-customcss is active!
```

The path in my VSC user settings is:
`"vscode_custom_css.imports": [
      "file://Volumes/Untitled/Users/joe/.vscodestyles.css"
    ],`

Where is the `Macintosh%20HD` in the first error coming from???

**Comment by squaredindex** [comment]
I'm not getting any errors in the console personally, just `[Extension Host] vscode-customcss is active!`.

Tried again with file in root but still, nothing changes.
```
 "vscode_custom_css.imports": [
    "file://~/.vscodestyles.css"
  ],
```

**Comment by squaredindex** [comment]
If I follow the link it brings me directly to the CSS file, so I must be missing something as to why I still get an error even when VSCode can locate the file inside the editor.
```
   "vscode_custom_css.imports": [
    "file://Volumes/Macintosh%20HD/Users/lev/vscodestyles.css"
  ],
```

`volumes/Macintosh%20HD/Users/lev/vscodestyles.css Failed to load resource: net::ERR_FILE_NOT_FOUND`

**Comment by wesbos** [comment]
Can you run `cat /Volumes/Macintosh%20HD/Users/lev/vscodestyles.css` ?

**Comment by squaredindex** [comment]
@wesbos Thanks so much Wes! 😃 That helped me troubleshoot it. I was ignorant of cat until now, still a noob.

The following has worked for me:
```
  "vscode_custom_css.imports": [
    "file://../Users/lev/.vscodestyles.css"
  ],
```

**Comment by wesbos** [comment]
Perhaps I shoudn't have made this a hidden file :)

**Comment by PGDJ** [comment]
I am now having trouble with this but I was not having any problems before. I had to reinstall the custom css and js extension and it has not worked since then.

**Comment by 1natsu172** [comment]
@PGDJ 
Is [vscode-custom-css](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) installed? :thought_balloon: 

```
"vscode_custom_css.imports": ["file:///Users/PGDJ/any-folders/vscode-custom.css"]
```
Then try type `file: ///` :keyboard:

**Comment by jeffreyscottfrench** [comment]
@PGDJ Not sure if you've fixed it yet, but I just went thru about an hour of trial and error for a similar problem, and I FINALLY remembered that you must re-execute "Reload Custom CSS and JS" from the command palette, and then it will work again.

**Comment by christianalares** [comment]
Tip if you are not sure how to write the path to your custom CSS file:
Open a new tab in chrome, press ⌘ + O (open file), navigate to the file and open it then copy URL and paste it to VSCode prefs.

**Comment by KDuverge** [comment]
Im having issues installing the vscode-custom-css plugin

**Comment by alernerdev** [comment]
Not having any luck with getting the custom CSS in my VSCode to work.

- I did install the custom css plugin -- getting "appears to be corrupt" message when launching vscode, so I guess "it works".
- my path to css file is "file:///home/alex/vscode-styling2.css" and I have verified its "correctness" by pasting into Firefox --- I am able to open the file
- the content of my file is copy/pasted version of cobalt2-custom-hacks.css file (version 2.1.6) + some other stuff.
So what piece of magic am I missing?   Is it possible that it does work, and I am just not seeing the changes?  What glaring piece of CSS can I put into the file to make it stand out (I am a total noob to Linux and Web dev, sorry)
Thank you

**Comment by bharat-patodi** [comment]
All the steps mentioned by @alernerdev + 

- disable custom css and js (I think I had enabled it during the process)
- close VS Code
- open VS Code
- enable custom css and js
- close and then start VS Code
(remember to open VS Code in admin mode, if in Windows)
Although you should be able to achieve the same result with "Reload Custom CSS and JS", strangely it didn't work for me, but disabling and then enabling custom CSS and JS sealed it. The dirty circle is now yellow. Thanks @wesbos for the cobalt2 theme.

**Comment by codebeeper** [comment]
Doesn't work.

**VSCode** Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-36-generic

**Comment by heweicong** [comment]
there are any examples of custom_css file  ?
