### ISSUE TITLE
Blade Syntax

### ISSUE THREAD

**Issue by jaydickinson** [wesbos/cobalt2-vscode#55]
Hey Wes, Love cobalt use it on everything, thanks!

Looking at switching to VS from Sublime and the syntax highlighting for blade on the cobalt theme doesn't seem to be working like it does on Sublime.

![screen shot 2017-09-26 at 15 18 21](https://user-images.githubusercontent.com/1121045/30865234-f8a7c81a-a2cd-11e7-9f62-56941a23d2c7.png)

![screen shot 2017-09-26 at 15 16 46](https://user-images.githubusercontent.com/1121045/30865198-dc7f324a-a2cd-11e7-8d4d-a6e9ca521edd.png)

cant seem to work out where to alter settings to get this to be a bit better using this for blade syntax: https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade. Any chance you could point me in the right direction if not something to do with this theme?

**Comment by jaydickinson** [comment]
had a look at this earlier I think adding something like the below helps

`    {
      "name": "Function name",
      "scope": "entity.name.function",
      "settings": {
        "fontStyle": "italic",
        "foreground": "#ffc600"
      }
    },`

probably without italics

![screen shot 2017-09-27 at 20 28 36](https://user-images.githubusercontent.com/1121045/30934058-3e4ffa30-a3c4-11e7-947a-0d935283c020.png)

**Comment by bivinvinod** [comment]
Was about to post this. Have the same issue.

**Comment by jonlow** [comment]
+1

**Comment by wesbos** [comment]
should be fixed in the latest. let me know if it isn't
