### ISSUE TITLE
Switches nearly not visible in VS Code terminal

### ISSUE THREAD

**Issue by iFarmGolems** [wesbos/cobalt2-vscode#57]
Basically this:

![2017-09-27 10_41_26-extension_ cobalt2 theme official microstep-mis-com visual studio code](https://user-images.githubusercontent.com/12659034/30904143-5ee9da16-a371-11e7-9aee-0f5837fba7aa.png)

Am I doing something wrong or is this how it is? (I am on windows powershell)

**Comment by samuelpath** [comment]
Same for me, you're doing nothing wrong.

**Comment by wesbos** [comment]
This is fixed in 2.1.5 :)

**Comment by samuelpath** [comment]
That was fast, thx Wes! 👍
