### ISSUE TITLE
Color contrast not strong enough for search option icons

### ISSUE THREAD

**Issue by samuelpath** [wesbos/cobalt2-vscode#58]
I find it hard to tell whether the "Match Case" & "Match Whole Word" for search are both ON or both OFF.

Here both are OFF:

![2017-09-27 15_48_37-customscript js packages visual studio code](https://user-images.githubusercontent.com/6030745/30919724-8849d2ae-a3a2-11e7-89a9-5c3825e2240e.png)

And here both are ON:

![2017-09-27 15_48_49-customscript js packages visual studio code](https://user-images.githubusercontent.com/6030745/30919725-8a52c70e-a3a2-11e7-969b-5cceb0dbfcf8.png)

To solve this, either the contrast between the shades of greys needs to be stronger, or other colors need to be chosen.

**Comment by wesbos** [comment]
Thanks! will have a look

**Comment by tombpl** [comment]
Similar issue when selecting a word, the other matching words are hard to see. I use the following setting to override the default highlight background color.

```
    "workbench.colorCustomizations": {
        "editor.selectionHighlightBackground": "#0050a4"
    }
```

**Comment by emanuel-lundman** [comment]
Noticed `inputOption.activeBorder` option can be set just like @tombpl did with `editor.selectionHighlightBackground`. 
Whilst waiting for a fix for this issue in the main theme.

**Comment by niklasfink** [comment]
The scrollbar had a very low contrast for me as well, so I added this:

```
  "workbench.colorCustomizations": {
    "scrollbarSlider.background": "#ffffff55",
    "scrollbarSlider.hoverBackground": "#ffffff77",
    "scrollbarSlider.activeBackground": "#bbbbff77"
  }
```

**Comment by wesbos** [comment]
@tombpl THanks - adding this to the theme
