### ISSUE TITLE
Whitespace not rendered with edtior.renderWhitespace set to boundary or all

### ISSUE THREAD

**Issue by mwidmann** [wesbos/cobalt2-vscode#6]
This is how it looks in other themes:

Indentation with Spaces:
<img width="251" alt="screen shot 2017-09-13 at 08 48 09" src="https://user-images.githubusercontent.com/251322/30363407-4da5512a-9860-11e7-96bc-9a6057c066b2.png">

Indentation with Tabs:
<img width="422" alt="screen shot 2017-09-13 at 08 49 05" src="https://user-images.githubusercontent.com/251322/30363454-78aff3c0-9860-11e7-93a3-b1bb5ada7139.png">

In Cobalt 2 neither the dot's nor the tabs are shown.

<img width="431" alt="screen shot 2017-09-13 at 08 51 08" src="https://user-images.githubusercontent.com/251322/30363503-b8a5c6ee-9860-11e7-8b3a-59f90e367d1d.png">

**Comment by odarriba** [comment]
+1!

**Comment by wesbos** [comment]
thanks - fixed in the next release!

**Comment by rodpoblete** [comment]
I have the same problem. wait for the new release :D

![1](https://user-images.githubusercontent.com/8984133/30391648-909d7d88-9890-11e7-9866-6a1292ea0539.png)
![2](https://user-images.githubusercontent.com/8984133/30391652-948bfb4a-9890-11e7-96b1-c10ef07b5ef8.png)
