### ISSUE TITLE
Find/Replace moda icons

### ISSUE THREAD

**Issue by glaszczyk** [wesbos/cobalt2-vscode#60]
Hello,
is there any chance to change color for active icons in Find/Replace modal?
Screenshot attached shows RegEx turned on but some color indication would be great.

![findreplace](https://user-images.githubusercontent.com/16131329/31117379-ea37ad02-a829-11e7-83c2-414642d286d1.png)

**Comment by onetrev** [comment]
Totally agree. This looks minor but it's pretty important I think. I was just about to post this same issue, because it's really hard to notice if you have Match Case or RegEx enabled, and that can really mess up your search.

**Comment by wesbos** [comment]
Thanks - anyone want to take a shot at this?

**Comment by onetrev** [comment]
I might be able to hack it next week or so. But I'm very new to VS Code so not 100% sure. Should be easy though, we just need to get the border / outline to be a much brighter blue or another colour. Maybe match the underline of colour of your active tab (which is what I see a majority of included themes do).

**Comment by onetrev** [comment]
Got it! I can do a pull request if you want, but it's just one line, if you just want to hack this in there. I'm good either way, just let me know.

Line 129 in `cobalt2.json` should be changed to:

`"inputOption.activeBorder": "#8DFFFF",`

I thought the blue here would be better than the yellow, as yellow is already used for the border on error messages / warnings in there, so it looks weird with the borders nearly touching.

Also noticed a tiny bug while I was hacking in there... Line 131 has this colour `"#ffc600dd"`  ... the "dd" should not be there of course.
