### ISSUE TITLE
Tag matching background needs higher contrast

### ISSUE THREAD

**Issue by jdhines** [wesbos/cobalt2-vscode#62]
The highlighting of matched tags in HTML/Handlebars, etc is extremely low contrast and almost impossible to see.

Cursor on the closing UL elment, opening tag highlighting is barely visible:
![html_tag_matching](https://user-images.githubusercontent.com/2855641/31498219-717d1818-af2f-11e7-94e4-c616b1d3f9ee.png)

Maybe a nice pale yellow or something?

**Comment by wesbos** [comment]
The yellow is too jarring - ideally this would be an underline but it's not possible.

You can override my settings in your own settings file so if you find something that is a good fit, please re-open this and let me know!

**Comment by jdhines** [comment]
Is it this setting?
`"editorBracketMatch.background": "#0d3a58",`

I put that in my User Settings, and it says that `editorBrackMatch.background` is an unknown configuration setting.

**Comment by jdhines** [comment]
Found this plugin in the meantime. 
https://github.com/vincaslt/vscode-highlight-matching-tag

Doesn't give the background unfortunately, but lets me easily identify the matching tag at least, which is all I'm going for. Maybe if the VSCODE team updates in the future, this style will be easier to change
