### ISSUE TITLE
Imperfect support of C#

### ISSUE THREAD

**Issue by lovestorymeetsvivalavida** [wesbos/cobalt2-vscode#65]
<img width="426" alt="0e3e2bbd-43c0-47d7-908f-142bfa1c9664" src="https://user-images.githubusercontent.com/9376212/31930603-da3c7054-b8d2-11e7-858e-4e619f1914a8.png">

**Comment by arturolinares** [comment]
Hey! Just sent a PR to add color to attributes (#89 ). 
<img width="643" alt="_untitled-1_ _cobalt2-vscode_ _visual_studio_code_y__extension_development_host__-_ _untitled-1_ _nsf_ _visual_studio_code" src="https://user-images.githubusercontent.com/203078/36056581-22a7da70-0dcb-11e8-9807-e1e714006de4.png">

**Comment by augustocdias** [comment]
Not only to C#, but also Java and C++...

**Comment by augustocdias** [comment]
So... I have forked and tried to fix the issue... But I was breaking the colors from the original theme. For that reason I have pushed my fork to vscode market until I manage to not break the original colors... It should work better with more languages... You can find it searching for cobalt2 fork
https://github.com/augustocdias/cobalt2-vscode
![code](https://user-images.githubusercontent.com/1080789/41222309-d0e86474-6d66-11e8-847b-e9542647fd16.png)
