### ISSUE TITLE
Git Diff Color Differentiator doesn't show up

### ISSUE THREAD

**Issue by dkvellin** [wesbos/cobalt2-vscode#66]
When you pull requests from GitHub and view the changes to accept the Incoming/Current changes... The default differentiator of VS Code with different background colors for Current and Incoming changes doesn't appear... It's very hard to view the code changes on the editor without these color differntiators

Link to how it should look - [https://code.visualstudio.com/images/versioncontrol_merge-conflict.png](url)

**Comment by noeladd** [comment]
@dkvellin I think this issue is referencing the same problem as #45

**Comment by wesbos** [comment]
Yep - closing a a dupe-  thanks!
