### ISSUE TITLE
Other instances of selected text not visible enough

### ISSUE THREAD

**Issue by MaurGi** [wesbos/cobalt2-vscode#67]
I love this theme - but when I select a variable, I cannot see the other instances that are going to be selected.

Is this the setting to change?
editor.selectionHighlightBackground

**Comment by mt-webdev** [comment]
Have you followed the 
"Recommended Settings" + "Important: CSS Hacks For Extra Sweet Editor"`?

i had the same issue and just used to theme to its finest instead of just 90% :)

**Comment by wesbos** [comment]
Yeah - or feel free to suggest a better colour and reopen :)
