### ISSUE TITLE
HTML closing tag selected color should be more deep.

### ISSUE THREAD

**Issue by zbandhan** [wesbos/cobalt2-vscode#68]
if the closing tag color was more deep to notice easily. Believe in you fix it. Thank you.

![tag](https://user-images.githubusercontent.com/10957285/32996371-0d3c6638-cdac-11e7-8ad3-18363a4c5808.png)

**Comment by zbandhan** [comment]
And have a look at editor text highlight color too.

**Comment by onetrev** [comment]
Totally agree! Doesn't have to be much deeper but definitely right now it's near impossible to see. Maybe you can do a quick pull request for that?

**Comment by wesbos** [comment]
Would love a PR for this

**Comment by Rayhatron** [comment]
Submitted a PR for this.
