### ISSUE TITLE
Searched text highlighted color is too closer to base color

### ISSUE THREAD

**Issue by foo-baar** [wesbos/cobalt2-vscode#7]
Hey Wes, I guess the image below to explain it all:
![screen shot 2017-09-13 at 2 35 13 pm](https://user-images.githubusercontent.com/13655874/30369050-ca5baa54-9890-11e7-83a0-bfc7572b6adf.png)

Thanks for the beautiful theme 👍.

Danke.

**Comment by wesbos** [comment]
Thoughts on this? I'd like a yellow border around matches but that isn't an option with VS code unless you use a CSS hack. 

![](http://wes.io/mTuc/what.gif)

**Comment by wesbos** [comment]
I've pushed this, but if anyone wants to try some other colours, feel free to try out and PR

**Comment by wesbos** [comment]
Mmmm gonna try this for a few days and see what I think

![](http://wes.io/mThC/content)

**Comment by palashmon** [comment]
+1 This is looking better than previous one where underlying text was not readable at all.

**Comment by foo-baar** [comment]
Hey Wes,

Sorry I was away, this looks perfect to me 👍

(BTW: Below are few archives from my experiment this morning (its night India now 🌚))

![screen shot 2017-09-13 at 11 30 36 pm](https://user-images.githubusercontent.com/13655874/30392931-fa976f1e-98db-11e7-9a3c-374f8f7b926a.png)


![screen shot 2017-09-13 at 11 27 08 pm](https://user-images.githubusercontent.com/13655874/30392909-e339d334-98db-11e7-9014-80c7b920c21d.png)

![screen shot 2017-09-13 at 11 28 53 pm](https://user-images.githubusercontent.com/13655874/30392921-edce447e-98db-11e7-9368-bee18a7cbc4c.png)
