### ISSUE TITLE
Background color in peek definition

### ISSUE THREAD

**Issue by arturolinares** [wesbos/cobalt2-vscode#70]
The background color of the symbol being "peeked" is black, making it very confusing because the peek frame is very dark (to open the peek definition _frame_, right click on a symbol a select _Peek Definition_).

<img width="556" alt="vendor_doctrine_instantiator_src_doctrine_instantiator_instantiator_php_ _stamper_ _visual_studio_code" src="https://user-images.githubusercontent.com/203078/33146607-7808580c-cf8a-11e7-8d3a-648d6599a051.png">

Can we make the background lighter than the editor background instead? 

Also, I think a yellow border highlighting the whole peek section would be useful too.

Thanks, and congratulations for your great theme!

**Comment by arturolinares** [comment]
Sent PR #77 to fix this.

**Comment by wesbos** [comment]
Thanks @arturolinares
