### ISSUE TITLE
Scrollbar bg-color

### ISSUE THREAD

**Issue by mt-webdev** [wesbos/cobalt2-vscode#71]
Hey everyone,
just wanted to point out that the background color of the scroll bar doesn't differentiate iteself enough from the editor background color. 

As you can see in the screenshot, on line 84 it took me a moment to realise that its just hidden behind the scrollbar.

THX for this awesome theme! 

> PS: probably gonna do my first PR in here? :D

![image](https://user-images.githubusercontent.com/6785503/33328024-312f3fee-d459-11e7-9a06-f48bb94bb453.png)

**Comment by wesbos** [comment]
please do send a PR :D

**Comment by mt-webdev** [comment]
tzzzz :D lazy you! will do so sir! 👍

**Comment by hnrchrdl** [comment]
I looked into this and unfortunatly it seems there is no way to change this. Minimap and scrollbar seem to inherit the editor background and you cannot give them a different backgrounds seperatly.

**Comment by wesbos** [comment]
thanks for looking into this :)
