### ISSUE TITLE
Statusbar goes dark when in debug mode

### ISSUE THREAD

**Issue by X-Tender** [wesbos/cobalt2-vscode#73]
I don't know if it's a bug or a feature but when you enter the Debug mode (F5) then the statusbar text color goes darker and is barely readable.
<img width="785" alt="normal" src="https://user-images.githubusercontent.com/1413979/33374148-3742deac-d505-11e7-839a-78e507c26b9c.png">
<img width="794" alt="debug" src="https://user-images.githubusercontent.com/1413979/33374149-375b2af2-d505-11e7-93f5-93b189870548.png">

**Comment by wesbos** [comment]
I think VS Code fixed this - it doesn't seem to do it  for me - please re-open if that is not the case in the latest updates

**Comment by cwadrupldijjit** [comment]
My status bar does this all the time, and has done it since I started using this theme.  Should I open another issue, or is there any other workaround?

I've been using the insiders builds on Windows.

**Comment by wesbos** [comment]
please do open an issue with some steps on how to get it to happen - will fix it!
