### ISSUE TITLE
Please update your doc: `vscode_custom_css.imports` accepts URLs, not file paths.

### ISSUE THREAD

**Issue by be5invis** [wesbos/cobalt2-vscode#79]

**Comment by be5invis** [comment]
Also, @clickys reported that your institutions are "confusing". You may need to refine it with simpler words and more clear steps.

**Comment by konti-dylan** [comment]
Example of URLs and file paths?

**Comment by be5invis** [comment]
URL: `file:///C:/Users/be5invis/.vscode.css`
File Path: `C:\Users\be5invis\.vscode.css`

**Comment by abdelrahmanrifai** [comment]
Yeah, for me only file URLs is working too.

Mac/Linux: `file:///Users/YOUR-PC-USERNAME/.vscodestyles.css`
Windows: `file:///C:/Users/YOUR-PC-USERNAME/.vscodestyles.css`

**Comment by wesbos** [comment]
@abdelrahmanrifai can you submit a PR?
