### ISSUE TITLE
editor.Ruler is too opaque

### ISSUE THREAD

**Issue by kmelve** [wesbos/cobalt2-vscode#9]
![image](https://user-images.githubusercontent.com/1131579/30374788-70a20c9c-9886-11e7-8df8-bc78a3753020.png)

A tad less colour would do the trick!

**Comment by odarriba** [comment]
+1!

**Comment by wesbos** [comment]
Will be fixed in the next release- thanks!

**Comment by wesbos** [comment]
![](http://wes.io/mTQ1/woah)
