### ISSUE TITLE
Inline URL coloring in markdown files are no longer working

### ISSUE THREAD

**Issue by nickjj** [wesbos/cobalt2-vscode#91]
Hey Wes,

I just noticed that inline URLs are not being colored up anymore with your theme for markdown files.

Here's a case where syntax highlighting works as expected:

```markdown

Hello world.

[link](#)
```

And here's a case where it fails (the link will be white text):

```markdown

Hello [world](#).
```

In the previous release both variants would have been colored up properly.

This is with using vscode insiders edition (1.21.0 built on Feb. 9th 2018).

**Edit:** Potential false alarm. I just tried a bunch of different official themes and I'm seeing the same result, so maybe something broke with the latest insider's build. Are you seeing the same result?

**Comment by cwadrupldijjit** [comment]
I've seen this, too, but I expect it might be a break in Code's side, with its markdown parser getting confused with anything that directly follows it.

**Comment by palashmon** [comment]
I think this is working fine now.

![code3](https://user-images.githubusercontent.com/14850464/46090938-6152af80-c1cf-11e8-8259-76457b7d2058.png)

Closing this issue for now, please reopen if that is not the case.
