### ISSUE TITLE
Upgrade from pre Jan 03 to current settings

### ISSUE THREAD

**Issue by mt-webdev** [wesbos/cobalt2-vscode#92]
As I just upgraded to the latest version of this theme I noticed that there are some kind of merge conflicts referring to the cursorWidth, cursorStyle.

Problem: 
Previously the cursor was set to underline-thin via user settings and styled into a fat-cursor via the custom css hacks.

Now after the cursor width etc. is styleable via the user settings itself users upgrading from previous versions will see a weird little dot like cursor.

How to resolve:
Probably we should move the cursor-styling out of the recommended settings and put it directly into the theme-settings.

**Comment by wesbos** [comment]
Hey - this is already done :) Thanks!

**Comment by mt-webdev** [comment]
I cannot find the code for cursorWidth in https://github.com/wesbos/cobalt2-vscode/blob/master/theme/cobalt2.json

But this would just be a luxury upgrade feature :)

**Comment by wesbos** [comment]
Check the readme :) 

```
  "editor.cursorStyle": "line",
  "editor.cursorWidth": 5,
  "editor.cursorBlinking": "solid",
```

**Comment by mt-webdev** [comment]
Thats what i tried to say :)

Its "only" in the readme. If you just click the update button in vs code for this theme, it will result in a weird dot-like cursor styling as the changes got removed of the css-hacks.css.

This would have been prevented if the edits from the readme would already be inside the cobalt2.json.

**Comment by wesbos** [comment]
Ohh gotcha - I don't think you can put those settings in the theme, can you?
