### ISSUE TITLE
Red colour in some folders/files

### ISSUE THREAD

**Issue by tekymonkey** [wesbos/cobalt2-vscode#93]
Not sure what means this "red" colour... As far as I see, there is any error on my code and everything works fine.

![screen shot 2018-02-19 at 17 06 22](https://user-images.githubusercontent.com/2632465/36386855-7dd09116-1597-11e8-9c51-f5bf84d64f70.png)
![screen shot 2018-02-19 at 17 06 37](https://user-images.githubusercontent.com/2632465/36386856-7debb298-1597-11e8-9539-af64e4e24c3a.png)

**Comment by wesbos** [comment]
This is a new feature in vs code where it highlights your gitn changes in the sidebar - nothing to do with the Cobalt2 theme 😃

**Comment by protoEvangelion** [comment]
You can change the color of ignored files in VS Code settings:

```
  "workbench.colorCustomizations": {
    "[Cobalt2]": {
      "gitDecoration.ignoredResourceForeground": "#808080",
    }
  },
```

The darker gray works nicely for me!

**Comment by sanfilippopablo** [comment]
@protoEvangelion That looks like it should be the default for me.

Any reason why ignored files are bright pink in this theme by default?

**Comment by protoEvangelion** [comment]
@sanfilippopablo Looks like bright pink is set here:
https://github.com/wesbos/cobalt2-vscode/blob/master/theme/cobalt2.json#L261
No idea why that would win over the default ignored file color though.
Do you have `gitDecoration.ignoredResourceForeground` set in in workspace, user, or folder settings by any chance?

**Comment by patotoma** [comment]
Not sure why this was closed if the problem still exists and it is clearly a theme setting. So I opened #140 with a fix.

**Comment by AlexVPopov** [comment]
I'd like to say, that I also experience this problem, so I hope that @patotoma #140 will soon be merged. Thank you.

**Comment by wesbos** [comment]
thanks folks! Merged that one in - will be out shortly
