### ISSUE TITLE
February 2018 1.21 VS Code Release — New Styling Options

### ISSUE THREAD

**Issue by plambhsa** [wesbos/cobalt2-vscode#95]
In the February 2018 1.21 release, new options were added for styling in VS Code themes. Here's a list of new options:

- `notificationCenter.border`: Notification Center border color.
- `notificationCenterHeader.foreground`: Notification Center header foreground color.
- `notificationCenterHeader.background`: Notification Center header background color.
- `notificationToast.border`: Notification toast border color.
- `notifications.foreground`: Notifications foreground color.
- `notifications.background`: Notifications background color.
- `notifications.border`: Notifications border color separating from other notifications in the Notification Center.
- `notificationLink.foreground`: Notification links foreground color.
- `editor.selectionHighlightBorder`: Border color for regions with the same content as the selection.
- `editor.wordHighlightBorder`: Border color of a symbol during read-access, for example when reading a variable.
- `editor.wordHighlightStrongBorder`: Border color of a symbol during write-access, for example when writing to a variable.
- `editor.findMatchBorder`: Border color of the current search match.
- `editor.findMatchHighlightBorder`: Border color of the other search matches.
- `editor.findRangeHighlightBorder`: Border color the range limiting the search (Enable 'Find in Selection' in the find widget).
- `editor.rangeHighlightBorder`: Background color of the border around highlighted ranges.
- `terminal.border`: The color of the border that separates split panes within the terminal. This defaults to panel.border.

![screenshot 5](https://user-images.githubusercontent.com/14982471/37124645-6596b288-2226-11e8-9629-cc3136c9b432.png)

**Comment by jeffreyscottfrench** [comment]
PR #97 - new Notification Center styles are added, with backwards compatibility for pre 1.21 left in as well.

**Comment by plambhsa** [comment]
In the 1.22 release, two new style options were added:

- `editorHint.foreground`: Foreground color of hints in the editor
- `editorHint.border`: Border color of hints in the editor

![screenshot 77](https://user-images.githubusercontent.com/14982471/38431341-293cbad6-3981-11e8-9fe1-6ff183a47cb1.png)
