### ISSUE TITLE
Status bar text goes dark in debug mode

### ISSUE THREAD

**Issue by cwadrupldijjit** [wesbos/cobalt2-vscode#96]
# Environment
## Platform:
Windows

#### Insiders:
>  Version 1.22.0-insider
> Commit 24d376c2735bb1eff8993aae6b3ba5eec967b6db
> Date 2018-03-08T05:17:47.706Z
> Shell 1.7.9
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64

#### Stable:
> Version 1.21.0
> Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
> Date 2018-03-07T11:04:09.969Z
> Shell 1.7.9
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64

# About:
When debugging a project in VS Code, the status bar changes colors.  I like it changing colors somewhat so I can tell if it's debugging, so that it changes colors isn't a problem to me, it's just that it changes to dark text on top of a dark background, making it very difficult to read.

I've seen this issue since I began using this theme a couple of weeks ago.  According to issue #73, it was a bug in Code that was supposed to be fixed by then, but I've seen this since I started using it, which was after that issue was closed.

## Steps to reproduce:
  1. Open up VS Code to a project you can debug inside of VS Code
  1. Start the debugger and wait until it has connected
  1. See that all of the text turns dark, and the status bar stays dark, making it difficult to read anything on it

## Screenshots:
Without debugger:  
![image](https://user-images.githubusercontent.com/13950768/37167504-546ea918-22bf-11e8-86f8-927845c69f1a.png)

With debugger:  
![image](https://user-images.githubusercontent.com/13950768/37167532-6aaff448-22bf-11e8-9cbc-193416a50544.png)

With debugger (Code stable release):
![image](https://user-images.githubusercontent.com/13950768/37168034-d57af146-22c0-11e8-8d9c-9f0b3c582341.png)

**Comment by jeffreyscottfrench** [comment]
Submitted a PR for this - pr# 98
