### ISSUE TITLE
Ligatures support

### ISSUE THREAD

**Issue by formspoint** [wesbos/cobalt2-vscode#99]
Can we get ligatures support like FiraCode in this theme? 

https://medium.com/@zamamohammed/multiple-fonts-alternative-to-operator-mono-in-vscode-7745b52120a0
https://medium.com/@docodemore/an-alternative-to-operator-mono-font-6e5d040e1c7e

**Comment by wesbos** [comment]
I dont think this is a theme thing, is it? More of a font thing

**Comment by Canadauni** [comment]
I'm not sure what @formspoint is looking for here. In terms of adding ligatures for Fira Code the setting I listed above just need to be added. If looking for the multi-font process as listed in the above articles I think this involves OP just figuring out how to change the custom css file to accommodate those changes as described in the linked articles. I don't think it has anything to do with this theme though.

**Comment by wesbos** [comment]
thanks @Canadauni  :)
